package:
  name: xi-cam
  version: 1.2.21

source:
  git_url: https://github.com/ronpandolfi/Xi-cam.git
  git_tag: dev

requirements:
  build:
    - python
    - setuptools
    - numpy ==1.10.4
    - cython

  run:
    - pyfits
    - python
    - scipy
    - pyside
    - tomopy
    - tifffile
    - cython
    - imageio
    - scikit-image
    - futures
    - appdirs
    - distributed
    - six
    - pyfai
    - qtconsole
    - nexusformat
    - qdarkstyle
    - pyqtgraph
    - matplotlib
    - h5py
    - pysftp
    - ipython
    - jupyter
    - numexpr
    - vispy

about:
  home: https://github.com/ronpandolfi/Xi-cam
