"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import sys
import glob
sys.setrecursionlimit(1500)


from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': False,
           'resources':['gui'],
           'iconfile': 'gui/icon.icns',
           'plist': {
                'CFBundleName': 'HiPIES',
                'CFBundleShortVersionString':'0.1.0', # must be in X.X.X format
                'CFBundleVersion': '0.1.0',
                'CFBundleIdentifier':'com.lbnl.hipies', #optional
                'NSHumanReadableCopyright': '@ 2015', #optional
                'CFBundleDevelopmentRegion': 'English', #optional - English is default
                },
            'includes' : [ 
                           'PySide.QtUiTools.QUiLoader', 'PySide.QtCore', 'PySide.QtGui',
                           'PySide.QtXml'
                         ],
                'packages' : [ 'pipeline', 'daemon', 'hipies' ]
            }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']

)
