"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import sys
sys.setrecursionlimit(1500)


from setuptools import setup

APP = ['hipies/main.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
           'resources': ['hipies/gui'],
           'iconfile':'hipies/gui/icon.icns',
           'plist': {
                'CFBundleName': 'HiPIES',
                'CFBundleShortVersionString':'0.1.0', # must be in X.X.X format
                'CFBundleVersion': '0.1.0',
                'CFBundleIdentifier':'com.lbnl.hipies', #optional
                'NSHumanReadableCopyright': '@ 2015', #optional
                'CFBundleDevelopmentRegion': 'English', #optional - English is default
                }
            }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'pyinstaller']

)
