import time
import tifffile
from os.path import splitext

from slacxop import Operation
import optools


class ReadTxtSSRL15(Operation):
    """Read a txtfile header generated by beamline 1-5 at SSRL.

    Returned as dictionary with predominantly float entries."""

    def __init__(self):
        input_names = ['file']
        output_names = ['header','header_file_name']
        super(ReadTxtSSRL15, self).__init__(input_names, output_names)
        self.input_doc['file'] = 'path to a text file header produced by beamline 1-5 at SSRL'
        self.output_doc['header'] = 'the header file as a python dictionary'
        # source & type
        self.input_src['file'] = optools.fs_input
        self.categories = ['INPUT.SSRL 1-5']

    def run(self):
        self.outputs['header_file_name'] = self.inputs['file']
        self.outputs['header'] = read_header(self.inputs['file'])


class ImageAndHeaderSSRL15(Operation):
    """Read an image and header generated by beamline 1-5 at SSRL.

    Returns ndarray image and dictionary header."""

    def __init__(self):
        input_names = ['file']
        output_names = ['image', 'header','image_file_name','header_file_name']
        super(ImageAndHeaderSSRL15, self).__init__(input_names, output_names)
        self.input_doc['file'] = 'path to a tif file image produced by beamline 1-5 at SSRL'
        self.output_doc['image'] = 'the image as an ndarray'
        self.output_doc['header'] = 'the header file as a python dictionary'
        # source & type
        self.input_src['file'] = optools.fs_input
        self.categories = ['INPUT.SSRL 1-5']

    def run(self):
        self.outputs['image_file_name'] = self.inputs['file']
        txtname = txtname_from_tifname(self.inputs['file'])
        self.outputs['header_file_name'] = txtname
        self.outputs['image'] = tifffile.imread(self.inputs['file'])
        print "image read from %s" % self.inputs['file']
        try:
            self.outputs['header'] = read_header(txtname)
            print "header read successfully"
        except IOError:
            print "No corresponding header to file %s was found." % self.inputs['file']
            self.outputs['header'] = {}
        except:
            print "some other error occured?"  ###
        print "ImageAndHeaderSSRL15 returning"



def txtname_from_tifname(tifname):
    txtname = splitext(tifname)[0] + '.txt'
    return txtname


def firstline_to_dict_entries(line, dict):
    """Splits apart the first line of header only."""
    entries = line.split(',')
    for ii in entries:
        ii = ii.strip()
    dict['User'] = entries[0][6:]
    dict['time'] = entries[1][6:]
    #dict['time'] = time_from_text(entries[1][6:])



def time_from_text(text):
    """Converts time from text to float.

    Not yet working; needs format info."""
    #format = ''
    timetuple = time.strptime(text, format)
    timefloat = time.strftime(format, timetuple)
    return timefloat


def line_to_dict_entries(line, sep, dict):
    """Reads 'Counters' and 'Motors' lines.

    Forces all to float type.  Changing to optional int format worth considering."""
    entries = line.split(',')
    for ii in entries:
        ii = ii.split(sep)
        key = ii[0].strip()
        value = float(ii[1].strip())
        #if int(value) == value:
        #    value = int(value)
        dict[key] = value


def read_header(txtfile):
    """Pulls together mini-functions in correct order."""
    print "read_header running"
    header = {}
    file = open(txtfile, 'r')
    file.readline()  # pass first, commented line
    line = file.readline()
    firstline_to_dict_entries(line, header)
    for i in range(3):
        line = file.readline()  # scroll forward to temp line
    header['temp_celsius'] = float(line[:-2])  # read temperature
    line = file.readline()
    print "looping over remainder" ###
    while len(line) > 0:
        print line
        if not (line[0] == '#'):
            if len(line.strip()) > 0:
                line_to_dict_entries(line, '=', header)
        line = file.readline()
    return header

def readfortest(imfile):
    image = tifffile.imread(imfile)
    txtname = txtname_from_tifname(imfile)
    try:
        header = read_header(txtname)
        print "header read successfully"
    except IOError:
        print "No corresponding header to file %s was found." % imfile
        header = {}
#    except:
#        print "some other error occured?"  ###
    print "readfortest returning"

'''
# change
imfile = "/Users/Amanda/Data20161118/R1/R1_2rdcool1_0001.tif"
readfortest(imfile)
'''