# -*- coding: utf-8 -*-
"""
@author: lbluque
"""
from copy import deepcopy
from pyqtgraph.parametertree import Parameter

BL832_FILE_DATA = [{'name': u'uuid', 'type': 'str', 'value': 'UUID'},
{'name': u'facility', 'type': 'str', 'value': 'als'},
{'name': u'end_station', 'type': 'str', 'value': 'bl832'},
{'name': u'owner', 'type': 'str', 'value': ''},
{'name': u'stage', 'type': 'str', 'value': 'raw'},
{'name': u'stage_version', 'type': 'str', 'value': 'bl832-1.0.0'},
{'name': u'stage_flow', 'type': 'str', 'value': '/raw'},
{'name': u'stage_date', 'type': 'str', 'value': ''},
{'name': u'dataset', 'type': 'str', 'value': ''}]

BL832_GROUP_DATA = [{'name': u'scanner', 'type': 'str', 'value': 'Advanced Light Source {LBL}\r'},
{'name': u'object', 'type': 'str', 'value': ''},
{'name': u'archdir', 'type': 'str', 'value': ''},
{'name': u'xtechdir', 'type': 'str', 'value': ''},
{'name': u'pfile', 'type': 'str', 'value': 'atrad\r'},
{'name': u'rfile', 'type': 'str', 'value': 'recobj\r'},
{'name': u'dtype', 'type': 'str', 'value':''},
{'name': u'stype', 'type': 'str', 'value': ''},
{'name': u'pgeometry', 'type': 'str', 'value': ''},
{'name': u'pfilegeom', 'type': 'str', 'value': ''},
{'name': u'sdate', 'type': 'str', 'value': ''},
{'name': u'experimenter', 'value': ''},
{'name': u'nangles', 'type': 'str', 'value': ''},
{'name': u'nslices', 'type': 'str', 'value': ''},
{'name': u'nrays', 'type': 'str', 'value': ''},
{'name': u'arange', 'type': 'str', 'value': '180.000000\r'},
{'name': u'pxcenter', 'type': 'str', 'value': ''},
{'name': u'pycenter', 'type': 'str', 'value': ''},
{'name': u'pzcenter', 'type': 'str', 'value': ''},
{'name': u'pxsize', 'type': 'str', 'value': ''},
{'name': u'pysize', 'type': 'str', 'value': ''},
{'name': u'pzsize', 'type': 'str', 'value': ''},
{'name': u'pxdist', 'type': 'str', 'value': ''},
{'name': u'pydist', 'type': 'str', 'value': ''},
{'name': u'pzdist', 'type': 'str', 'value': ''},
{'name': u'rxsize', 'type': 'str', 'value': ''},
{'name': u'rysize', 'type': 'str', 'value': ''},
{'name': u'rzsize', 'type': 'str', 'value': ''},
{'name': u'rxdist', 'type': 'str', 'value': ''},
{'name': u'rydist', 'type': 'str', 'value': ''},
{'name': u'rzdist', 'type': 'str', 'value': ''},
{'name': u'bgeometry', 'type': 'str', 'value': ''},
{'name': u'senergy', 'type': 'str', 'value': ''},
{'name': u'scurrent', 'type': 'str', 'value': ''},
{'name': u'dxelements', 'type': 'str', 'value': '2560\r'},
{'name': u'dzelements', 'type': 'str', 'value': '2160\r'},
{'name': u'dxfov', 'type': 'str', 'value': '2.585160\r'},
{'name': u'dzfov', 'type': 'str', 'value': '1.723440\r'},
{'name': u'xoffset', 'type': 'str', 'value': '1\r'},
{'name': u'yoffset', 'type': 'str', 'value': '1\r'},
{'name': u'rxelements', 'type': 'str', 'value': '2560\r'},
{'name': u'rzelements', 'type': 'str', 'value': '2160\r'},
{'name': u'ryelements', 'type': 'str', 'value': '2560\r'},
{'name': u'dxsize', 'type': 'str', 'value': ''},
{'name': u'dzsize', 'type': 'str', 'value': ''},
{'name': u'dxdist', 'type': 'str', 'value': '0.000000\r'},
{'name': u'dzdist', 'type': 'str', 'value': '0.000000\r'},
{'name': u'evalxstrt', 'type': 'str', 'value': '0\r'},
{'name': u'evalystrt', 'type': 'str', 'value':  '0\r'},
{'name': u'evalxsize', 'type': 'str', 'value': '0\r'},
{'name': u'evalysize', 'type': 'str', 'value': '0\r'},
{'name': u'cdtype', 'type': 'str', 'value': 'Remote Control\r'},
{'name': u'cdmaterial', 'type': 'str', 'value': 'LEAD\r'},
{'name': u'cdxsize', 'type': 'str', 'value': 'variable\r'},
{'name': u'cdzsize', 'type': 'str', 'value': 'variable\r'},
{'name': u'cddepth', 'type': 'str', 'value': '10.000000\r'},
{'name': u'obstime', 'type': 'str', 'value': '0.500000\r'},
{'name': u'naverages', 'type': 'str', 'value': '1\r'},
{'name': u'xbin', 'type': 'str', 'value': '1\r'},
{'name': u'ybin', 'type': 'str', 'value': '1\r'},
{'name': u'cooler_on', 'type': 'str', 'value': '1\r'},
{'name': u'cooler_target', 'type': 'str', 'value': '0.000000\r'},
{'name': u'diglev', 'type': 'str', 'value': '0\r'},
{'name': u'cammode', 'type': 'str', 'value': '0\r'},
{'name': u'ofactor', 'type': 'str', 'value': '0.000000\r'},
{'name': u'sfactor', 'type': 'str', 'value': '0.000000\r'},
{'name': u'stgsel', 'type': 'str', 'value': '0\r'},
{'name': u'stepdeg', 'type': 'str', 'value': '0.000000\r'},
{'name': u'rorder', 'type': 'str', 'value': '45\r'},
{'name': u'noisesig', 'type': 'str', 'value': '0.001500\r'},
{'name': u'rfilter', 'type': 'str', 'value': 'BUTTER\r'},
{'name': u'rfcutoff', 'type': 'str', 'value': '0.500000\r'},
{'name': u'rforder', 'type': 'str', 'value': '10\r'},
{'name': u'i0hmove', 'type': 'str', 'value': '0.000000\r'},
{'name': u'i0vmove', 'type': 'str', 'value': '-3.000000\r'},
{'name': u'i0cycle', 'type': 'str', 'value': '0\r'},
{'name': u'tile_xnumimg', 'type': 'str', 'value': '0\r'},
{'name': u'tile_ynumimg', 'type': 'str', 'value': '0\r'},
{'name': u'tile_xorig', 'type': 'str', 'value': '0.000000\r'},
{'name': u'tile_yorig', 'type': 'str', 'value': '0.000000\r'},
{'name': u'tile_xmovedist', 'type': 'str', 'value': '0.000000\r'},
{'name': u'tile_ymovedist', 'type': 'str', 'value': '0.000000\r'},
{'name': u'tile_xoverlap', 'type': 'str', 'value': '4\r'},
{'name': u'tile_yoverlap', 'type': 'str', 'value': '0\r'},
{'name': u'scan_then_tile', 'type': 'str', 'value': '1\r'},
{'name': u'new_dirs_per_scan', 'type': 'str', 'value': '1\r'},
{'name': u'axis1pos', 'type': 'str', 'value': '-0.000043\r'},
{'name': u'axis2pos', 'type': 'str', 'value': '0.000000\r'},
{'name': u'axis3pos', 'type': 'str', 'value': '77.138400\r'},
{'name': u'axis4pos', 'type': 'str', 'value': '83.667000\r'},
{'name': u'axis5pos', 'type': 'str', 'value': '0.000000\r'},
{'name': u'axis6pos', 'type': 'str', 'value': '10.572052\r'},
{'name': u'auto_eval_roi', 'type': 'str', 'value': '1\r'},
{'name': u'usebrightexpose', 'type': 'str', 'value': '0\r'},
{'name': u'brightexptime', 'type': 'str', 'value': '200.000000\r'},
{'name': u'phase_filt', 'type': 'str', 'value': '0\r'},
{'name': u'remove_outliers', 'type': 'str', 'value': '0\r'},
{'name': u'simple_ring_removal', 'type': 'str', 'value': '0\r'},
{'name': u'normalize_by_ROI', 'type': 'str', 'value': '0\r'},
{'name': u'Reconstruction_Type', 'type': 'str', 'value': 'Octopus\r'},
{'name': u'ring_removal_method', 'type': 'str', 'value': 'Octopus\r'},
{'name': u'distance', 'type': 'str', 'value': '20.000000\r'},
{'name': u'beta', 'type': 'str', 'value': '1.000000\r'},
{'name': u'delta', 'type': 'str', 'value': '1.000000\r'},
{'name': u'radius', 'type': 'str', 'value': '2.000000\r'},
{'name': u'threshold', 'type': 'str', 'value': '1000.000000\r'},
{'name': u'kernel_size', 'type': 'str', 'value': '0.000000\r'},
{'name': u'exclude_selected_projections', 'type': 'str', 'value': '0.000000\r'},
{'name': u'normalization_ROI_left','type': 'str', 'value':  '1.000000\r'},
{'name': u'normalization_ROI_right', 'type': 'str', 'value': '1.000000\r'},
{'name': u'normalization_ROI_top', 'type': 'str', 'value': '1.000000\r'},
{'name': u'normalization_ROI_bottom', 'type': 'str', 'value': '1.000000\r'},
{'name': u'output_type', 'type': 'str', 'value': '0.000000\r'},
{'name': u'output_scaling_min_value', 'type': 'str', 'value': '0.000000\r'},
{'name': u'output_scaling_max_value', 'type': 'str', 'value': '0.000000\r'},
{'name': u'low_ring_value', 'type': 'str', 'value': '-100.000000\r'},
{'name': u'upp_ring_value', 'type': 'str', 'value': '300.000000\r'},
{'name': u'max_ring_size', 'type': 'str', 'value': '100.000000\r'},
{'name': u'max_arc_length', 'type': 'str', 'value': '30.000000\r'},
{'name': u'ring_threshold', 'type': 'str', 'value': '300.000000\r'},
{'name': u'camera_used', 'type': 'str', 'value': 'PCO_Edge\r'},
{'name': u'projection_mode', 'type': 'str', 'value': 'Continuous Tomo\r'},
{'name': u'num_dark_fields', 'type': 'str', 'value': '10\r'},
{'name': u'dark_num_avg_of', 'type': 'str', 'value': '1\r'},
{'name': u'num_bright_field', 'type': 'str', 'value': '10\r'},
{'name': u'bright_num_avg_of', 'type': 'str', 'value': '1\r'},
{'name': u'frsum', 'type': 'str', 'value': '0\r'},
{'name': u'time_elapsed', 'type': 'str', 'value': '0.010851\r'},
{'name': u'time_stamp', 'type': 'str', 'value': '8/20/2015 12:43:52 PM\r'},
{'name': u'TC0', 'type': 'str', 'value': '2404.407269\r'},
{'name': u'TC1', 'type': 'str', 'value': '2404.407269\r'},
{'name': u'TC2', 'type': 'str', 'value': '34.728444\r'},
{'name': u'TC3', 'type': 'str', 'value': '35.599414\r'},
{'name': u'Mono_Energy', 'type': 'str', 'value': '19999.630063\r'},
{'name': u'Beam_Current', 'type': 'str', 'value': '500.731055\r'},
{'name': u'Izero', 'type': 'str', 'value': '-0.916141\r'},
{'name': u'Dark_Offset', 'type': 'str', 'value': '100.000000\r'},
{'name': u'optics_type', 'type': 'str', 'value': 'Optique\r'},
{'name': u'lens_name', 'type': 'str', 'value': 'Optique 10X\r'},
{'name': u'scintillator_name', 'type': 'str', 'value': '20 um LuAG\r'},
{'name': u'tilt', 'type': 'str', 'value': '2.806000\r'},
{'name': u'nhalfCir', 'type': 'str', 'value': '3\r'},
{'name': u'multiRev', 'type': 'str', 'value': '0\r'},
{'name': u'Lead_Flag', 'type': 'str', 'value': '-1.887500\r'},
{'name': u'turret1', 'type': 'str', 'value': '-0.380100\r'},
{'name': u'turret2', 'type': 'str', 'value': '0.662050\r'},
{'name': u'Z2', 'type': 'str', 'value': '208.676000\r'},
{'name': u'Horiz_Slit_A_Wall', 'type': 'str', 'value': '-3.500325\r'},
{'name': u'Horiz_Slit_A_Door', 'type': 'str', 'value': '6.500525\r'},
{'name': u'Horiz_Slit_Pos', 'type': 'str', 'value': '1.500100\r'},
{'name': u'Horiz_Slit_Size', 'type': 'str', 'value': '10.000850\r'},
{'name': u'Filter_Motor', 'type': 'str', 'value': '0.000000\r'},
{'name': u'postImageDelay', 'type': 'str', 'value': '0.000000\r'},
{'name': u'Camera_Z_Support', 'type': 'str', 'value': '76.896310\r'},
{'name': u'blur_limit', 'type': 'str', 'value': '100.000000\r'}]

BL832_PROJ_DATA = (deepcopy(BL832_GROUP_DATA) +
[{'name': u'name', 'type': 'str', 'value': 'sample0'}] +
[{'name': u'dim1', 'type': 'int', 'value': 1}] +
[{'name': u'dim2', 'type': 'int', 'value': 2160}] +
[{'name': u'dim3', 'type': 'int', 'value': 2560}] +
[{'name': u'title', 'type': 'str', 'value': 'image'}] +
[{'name': u'date', 'type': 'str', 'value': ''}] +
[{'name': u'errorFlag', 'type': 'int', 'value': 0}])

BL832_PARAMS = [Parameter(name='File Attributes', type='group', children=BL832_FILE_DATA, expanded=False),
                Parameter(name='Group Attributes', type='group', children=BL832_GROUP_DATA, expanded=False)]
                # Parameter(name='Projection Attributes', type='group', children=BL832_PROJ_DATA, expanded=False)]